### ISSUE TITLE
Files original names. 

### ISSUE THREAD

**Issue by Clouddark75** [Un-index/imgbb-bulk#2]
Hello, thank you so much for making this.

Is there any chance of getting the files names instead of the URL names of the links?

That will be pretty handy, I use Imgbb for storage, and it's complicated to renamed hundreds of files.

But if it can't be implemented, it's all good. I love the easy you can download via your website. Windows for some reason don't let me open the ".exe" one.

**Comment by deontic** [comment]
Hi, making it so the downloaded files keep their original names instead of urls is certainly possible, I’ll get it done soon. For some reason this issue didn’t appear in my notifications, so I’m sorry for the late response.

**Comment by deontic** [comment]
I've implemented this for the web version and the npm version. I might do it for the exe version as well if need be. Thanks for the suggestion.
