### ISSUE TITLE
The package does not work for me.

### ISSUE THREAD

**Issue by zns-commits** [Un-index/imgbb-bulk#3]
Hello, I tried your package with the same example script you put in the documentation.

I simply replaced your links with my own:
I put here the script :
```js
const imgbulk = require("@un-index/imgbb-bulk")

const urls = `https://ibb.co/vjsWTxP
https://ibb.co/GJJ0T5g
https://ibb.co/HKPfJG8
https://ibb.co/0jxMFvW
https://ibb.co/pJT1hy8
https://ibb.co/Kb4NVL1
https://ibb.co/K7p6PZ0
https://ibb.co/FB6DSTz
https://ibb.co/JcR7K3y
https://ibb.co/VNBHmkn
https://ibb.co/nRv7Q3X`;

imgbulk(urls);
```

I then ran the command "node index.js".
and here is the error I got :

<pre><font color="#00CD00"><b>jb@Aspire-E5-571G</b></font>:<font color="#0000EE"><b>~/Téléchargements/npm</b></font>$ node index.js
/home/jb/Téléchargements/npm/node_modules/@un-index/imgbb-bulk/index.js:30
                let name = doc.match(/data-text=&quot;image-title&quot;&gt;(.*)&lt;/)[1]
                                                                     ^

TypeError: Cannot read properties of null (reading &apos;1&apos;)
    at /home/jb/Téléchargements/npm/node_modules/<u style="text-decoration-style:single">@un-index</u>/imgbb-bulk/index.js:30:70
<font color="#7F7F7F">    at processTicksAndRejections (node:internal/process/task_queues:96:5)</font>
</pre>

Can you help me please?

Thank you for your help.

**Comment by deontic** [comment]
Sorry for the late reply. You can try out the web version for now: https://un-index.github.io/imgBB-web-bulk-downloader/

Not sure why this isn't working I'll take a look at it later.

**Comment by deontic** [comment]
The issue was with the latest npm version using original image names for the downloaded filenames .
Temporary fix would be to use the version published right before that one:

```js
npm uninstall @un-index/imgbb-bulk
npm i https://github.com/Un-index/npm-imgbb-bulk-downloader
```

**Comment by deontic** [comment]
Just fixed it. You can now use the regular npm version (make sure you have the latest version) and it retains original filenames.
